version: '3.7'

services:
  web:
    build:
      context: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-http.rule=Host(`api.localhost`)
      - traefik.http.routers.web-http.entrypoints=web
      - traefik.http.routers.web-http.middlewares=redirect
      - traefik.http.routers.web-https.rule=Host(`api.localhost`)
      - traefik.http.routers.web-https.entrypoints=websecure
      - traefik.http.routers.web-https.tls=true
      - traefik.http.routers.web-https.tls.certresolver=letsencrypt
      - traefik.http.services.web.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect.redirectscheme.scheme=websecure
    command: >
      sh -c "python manage.py migrate &&
             python manage.py w8_4_db &&
             python manage.py collectstatic &&
             gunicorn My24h.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    expose:
      - 8000
    volumes:
      - static:/static/
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql/
    env_file:
      - .env.db

  nginx:
    build: ./nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-http.rule=Host(`api.localhost`)
      - traefik.http.routers.nginx-http.entrypoints=web
      - traefik.http.routers.nginx-http.middlewares=redirect
      - traefik.http.routers.nginx-https.rule=Host(`api.localhost`) && PathPrefix(`/static/`)
      - traefik.http.routers.nginx-https.entrypoints=websecure
      - traefik.http.routers.nginx-https.tls=true
      - traefik.http.routers.nginx-https.tls.certresolver=letsencrypt
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect.redirectscheme.scheme=websecure
    restart: always
    volumes:
      - static:/static/
    depends_on:
      - web

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8888
    depends_on:
      - db

volumes:
  static:
  mariadb_data: