# Generated by Django 3.2 on 2021-04-20 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_type', models.CharField(max_length=30)),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
                ('km_points', models.FloatField(default=0)),
                ('elevation_gain_coeff', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('join_code', models.CharField(max_length=50, verbose_name='Join Code')),
                ('race_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.race')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_auth', models.JSONField(blank=True)),
                ('birthdate', models.DateField()),
                ('point', models.PositiveIntegerField(default=0)),
                ('team_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_date', models.DateTimeField()),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('distance', models.PositiveIntegerField()),
                ('positive_elevation_gain', models.PositiveIntegerField()),
                ('negative_elevation_gain', models.PositiveIntegerField()),
                ('run_time', models.DurationField()),
                ('avg_speed', models.FloatField()),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.runner')),
            ],
        ),
    ]
