# Generated by Django 3.2 on 2021-04-24 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.TextField(max_length=500)),
                ('nb_participants', models.IntegerField()),
            ],
            options={
                'ordering': ['nb_participants'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
                ('km_points', models.FloatField(default=0)),
                ('elevation_gain_coeff', models.FloatField(default=0)),
                ('duration_gain_coeff', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('join_code', models.CharField(max_length=50, verbose_name='Join Code')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.category')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.race')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('birthday', models.DateField()),
                ('strava_auth', models.JSONField(blank=True)),
                ('admin', models.BooleanField(default=False)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='api.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Racer',
                'verbose_name_plural': 'Racers',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2021, 4, 24, 7, 21, 9, 699498, tzinfo=utc))),
                ('distance', models.FloatField()),
                ('positive_elevation_gain', models.PositiveIntegerField()),
                ('negative_elevation_gain', models.PositiveIntegerField()),
                ('run_time', models.DurationField()),
                ('avg_speed', models.FloatField()),
                ('point', models.IntegerField()),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.racer')),
            ],
        ),
    ]
