# Generated by Django 3.2 on 2021-04-24 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activity_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 7, 21, 43, 457907, tzinfo=utc)),
        ),
    ]
